export const guides = [
    {
        id: 'asdf',
        title: 'World Bosses',
        content: 'Locations, tips, loot',
        rating: 8,
        author: 'Veniamine',
        categories: 'encounters',
        image: 'https://steamuserimages-a.akamaihd.net/ugc/942831990284595022/1EA4186A9E41049CFCD62EDB5BBC624CA0A484E8/?imw=512&&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false',
        thumbnail: 'https://steamuserimages-a.akamaihd.net/ugc/942831990284595022/1EA4186A9E41049CFCD62EDB5BBC624CA0A484E8/?imw=512&&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false',
    },
    {
        id: 'klmn',
        title: 'Sandswept Ruins',
        content: 'Lorem sapiente deleniti laborum eius nisi!',
        rating: 5,
        author: 'theSilentSeeker',
        categories: 'maps',
        image: '../../assets/7.jpg',
        thumbnail: 'https://images.mein-mmo.de/medien/2018/04/Conan-Exiles-Conan-vs-Viech.jpg',
    },
    {
        id: 'dddg',
        title: 'Where to find cobra eggs',
        content: 'Lorem adipisicing elit.',
        rating: 2,
        author: 'carusell',
        categories: 'pets',
        image: 'https://i.redd.it/meet-apep-and-quetzalcoatl-amazing-rolls-of-greater-snakes-v0-zht1muyd90rb1.png?width=1918&format=png&auto=webp&s=02da320a0e68ef4c24e271166565de50f9ff2254',
        thumbnail: 'https://i.redd.it/meet-apep-and-quetzalcoatl-amazing-rolls-of-greater-snakes-v0-zht1muyd90rb1.png?width=1918&format=png&auto=webp&s=02da320a0e68ef4c24e271166565de50f9ff2254',
    },
    {
        id: 'opjk',
        title: '2024 Beginners Guide',
        content: 'Lorem ottomini polet.',
        rating: 7,
        author: 'shorty',
        categories: 'gameplay',
        image: 'https://assetsio.reedpopcdn.com/survive-conan-exiles-bad-introduction-and-theres-real-promise-there-1486717167777.jpg?width=1200&height=1200&fit=bounds&quality=70&format=jpg&auto=webp',
        thumbnail: 'https://assetsio.reedpopcdn.com/survive-conan-exiles-bad-introduction-and-theres-real-promise-there-1486717167777.jpg?width=1200&height=1200&fit=bounds&quality=70&format=jpg&auto=webp',
    },
    {
        id: 'ccvd',
        title: 'Building and Decorations',
        content: 'Opus 8 commetinus emet',
        rating: 6,
        author: 'mcKhan',
        categories: 'building',
        image: 'https://pbs.twimg.com/media/EJVxTYnXsAMEvW6.jpg:large',
        thumbnail: 'https://pbs.twimg.com/media/EJVxTYnXsAMEvW6.jpg:large',
    },

];
